### ISSUE TITLE
Ezért vannak modelljeink

### ISSUE THREAD

**Issue by bence04** [enco-2019-team1/UnderseaGame#11]
https://github.com/enco-2019-team1/UnderseaGame/blob/5b0dd393a45eb3afae670820f7251358903ca0d7/frontend/src/app/core/registry/component/registry.component.ts#L23-L26

Ha [(ngModel)]-ben a modelledet adod meg akkor ez teljesen kihagyható és nem kell ez a sok segédváltozó

Például:
`[(ngModel)]="user.name`"

**Comment by Krauszzsolt** [comment]
Javítottam.
