### ISSUE TITLE
CSS osztálynevek elnevezése

### ISSUE THREAD

**Issue by bence04** [enco-2019-team1/UnderseaGame#8]
https://github.com/enco-2019-team1/UnderseaGame/blob/5b0dd393a45eb3afae670820f7251358903ca0d7/frontend/src/app/core/login/component/login.component.html#L21

Kerüljük az ilyen "first-button" és "second-button" típusú osztályneveket :D inkább "login-button" meg "registry-button" hogy könnyebben olvasható legyen

**Comment by Krauszzsolt** [comment]
Elvileg mindenhol javítottam a hasonlókat.
