### ISSUE TITLE
Háttérkép méretezése

### ISSUE THREAD

**Issue by bence04** [enco-2019-team1/UnderseaGame#9]
https://github.com/enco-2019-team1/UnderseaGame/blob/5b0dd393a45eb3afae670820f7251358903ca0d7/frontend/src/app/core/login/component/login.component.scss#L9

A 100% 100% képes szétnyújtani a képet, így neked valószínű cover kell majd ([itt kirpóbálhatod a különséget](https://www.w3schools.com/cssref/playit.asp?filename=playcss_background-size&preval=cover)), illetve, ha teljesen kitölti a háttér a képernyőt, mert background-size-zal kikényszeríted akkor a background-repeat elhagyható

**Comment by Krauszzsolt** [comment]
Mindenhol javítottam
